FROM python:3.10.12-bullseye

WORKDIR /app

COPY ./requirements.txt /app

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     libpq-dev \
#     python3-dev \
#     python3-pip \
#     python3-setuptools \
#     python3-wheel \
#     && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y python3-dev

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . /app

EXPOSE 5000

CMD ["python3", "-m", "services.server"]